# Generated by Django 4.2 on 2023-05-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
